apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata: 
      name: nginx
      labels:
        app: nginx
        tier: front-end
    spec: 
      containers:
      - name: nginx
        image: nginx  
  replicas: 3
  selector: 
    matchLabels:
      type: front-end